name: finance_informator
description: "finance_informator"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.3.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dotted_border: ^2.1.0
  dotted_line: ^3.2.3
  image_picker: ^1.1.2
  url_launcher:
  fl_chart: ^0.69.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Inter400
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Inter500
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: Inter600
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: Inter700
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf